### ISSUE TITLE
Get record from sd card

### ISSUE THREAD

**Issue by eerison** [dbuezas/icsee-ptz#17]
Hello @dbuezas it's me again

Do you have any idea how to get videos saved in `sd card`? should it be via `rtsp` ?

I would like to have the playback functionality

**Comment by dbuezas** [comment]
Unfortunately non trivial and I won't realistically ever get to it.

I suggest you try recording them in the home assistant computer (look for motioneye or frigate add ons)

Otherwise, if you don't want to use the standard mobile app, there is XMEye which has both desktop and mobile apps. You may even be able to start recording only when a motion alarm triggers to keep network usage low (if you do, please do share what you did :) )

If you do some programming, the python library I use to communicate with the camera does have some basic file support, so it may be possible to implement this using it. It is called python-dvrip.

Sorry

**Comment by eerison** [comment]
Hey @dbuezas

I found a comment in this post : https://github.com/NeiroNx/python-dvr/issues/38#issuecomment-1465227288

One guy could download the files, but he is using other lib :'(

**Comment by dbuezas** [comment]
Oh I didn't know that library, thanks for sharing. I wonder if I could use it from the integration. My implementation includes some workarounds for issues with the python library which the go library likely doesn't have
